services:
  postgres:
    image: postgres:15
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=danila
      - POSTGRES_PASSWORD=bmws1000rr
      - POSTGRES_DB=mydb
    ports:
      - "54321:5432"

  flask:
    build: 
      dockerfile: Dockerfile
      context: .
    container_name: flask
    volumes:
      - uploads_data:/app/app/static/upload
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - KEY=${KEY}
    depends_on:
      - postgres
    expose:
      - 8080

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - uploads_data:/app/static/upload  # та же папка что и у Flask
    depends_on:
      - flask
    ports:
      - "8080:80"

volumes:
  postgres_data:
  uploads_data: